name: Hello World - Node JS - Docker Compose 

on:
  push:
    paths:
      - "hello-world/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Test
        run: |
          docker compose -f ./hello-world/docker-compose-dev.yaml up -d
